services:
  incite_pg:
    image: postgres:17-alpine
    container_name: incite_pg
    restart: always
    environment:
      POSTGRES_DB: incite
      POSTGRES_USER: incite
      POSTGRES_PASSWORD: incite
    volumes:
      - ./pg_data:/var/lib/postgresql/data # a pasta pg_data tem que ir pro gitignore
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U incite -d incite"]
      interval: 5s
      timeout: 2s
      retries: 20

  incite_pg_migrate:
    container_name: incite_pg_migrate
    image: node:22.17.0-alpine
    volumes:
      - ./prisma/:/prisma
    working_dir: /prisma
    env_file: .env
    command: corepack enable && pnpm dlx prisma db push
    depends_on:
      incite_pg:
        condition: service_healthy

  incite_backend:
    container_name: incite_backend
    restart: always
    build:
      context: .
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      incite_pg_migrate:
        condition: service_completed_successfully
